include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-custom-image.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/maintenance.yml'

stages:
  - pre-package
  - package
  - post-package
  - deploy
  - maintenance

variables:
  PROJECT_PARENT_NAME: postgres

.deploy:
  variables:
    STACK: ${PROJECT_PARENT_NAME}
    SERVICES_TO_CHECK: ${PROJECT_PARENT_NAME}_${CI_PROJECT_NAME}

.deploy-development:
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}.tmpl.yml:docker-compose.${CI_PROJECT_NAME}.dev.yml
  environment:
    name: dev/${CI_PROJECT_NAME}

.deploy-production:
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}.tmpl.yml:docker-compose.${CI_PROJECT_NAME}.prod.yml
  environment:
    name: pro/${CI_PROJECT_NAME}

.deploy-backup:
  variables: &deploy-backup-variables
    SERVICES_TO_CHECK: ${PROJECT_PARENT_NAME}_backup-db
    DD_AWS_REGION: ${AWS_REGION}

.deploy-backup-development:
  extends: .deploy-development
  variables:
    COMPOSE_FILE: docker-compose.backup-db.tmpl.yml:docker-compose.backup-db.dev.yml
    <<: *deploy-backup-variables
  environment:
    name: dev/backup-db

.deploy-backup-production:
  extends: .deploy-production
  variables:
    COMPOSE_FILE: docker-compose.backup-db.tmpl.yml:docker-compose.backup-db.prod.yml
    <<: *deploy-backup-variables
  environment:
    name: pro/backup-db

.deploy-backup-support-branch: &deploy-backup-support-branch
  only:
    - branches
  except:
    - master
    - schedules

deploy-backup-support-branch-development:
  extends: .deploy-backup-development
  <<: *deploy-backup-support-branch

.deploy-backup-stable-branch: &deploy-backup-stable-branch
  only:
    - master
  except:
    - schedules

deploy-backup-stable-branch-development:
  extends: .deploy-backup-development
  <<: *deploy-backup-stable-branch

deploy-backup-stable-branch-production:
  extends: .deploy-backup-production
  <<: *deploy-backup-stable-branch

.deploy-backup-tag: &deploy-backup-tag
  only:
    - tags

deploy-backup-tag-development:
  extends: .deploy-backup-development
  <<: *deploy-backup-tag

deploy-backup-tag-production:
  extends: .deploy-backup-production
  <<: *deploy-backup-tag

.scheduled-run:
  variables:
    STACK: ${PROJECT_PARENT_NAME}
    SERVICE: ${PROJECT_PARENT_NAME}_backup-db

scheduled-run-development:
  script: ':'
