include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-custom-image.yml'
  - project: 'redmic-project/postgres/backup-db'
    ref: dev
    file: '/backup-db-deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/maintenance.yml'

stages:
  - pre-package
  - package
  - post-package
  - deploy
  - deploy-backup-db
  - maintenance

variables:
  PROJECT_PARENT_NAME: postgres
  DEVELOPMENT_MAINTENANCE_DISABLED: 'true'

.deploy:
  variables:
    STACK: ${PROJECT_PARENT_NAME}

.deploy-development:
  environment:
    name: dev/${CI_PROJECT_NAME}

.deploy-production:
  environment:
    name: pro/${CI_PROJECT_NAME}

.deploy-backup-db:
  variables:
    STACK: ${PROJECT_PARENT_NAME}
    DD_AWS_REGION: ${AWS_REGION}

.scheduled-run:
  variables:
    STACK: ${PROJECT_PARENT_NAME}
    SERVICE: ${PROJECT_PARENT_NAME}_backup-db
