version: '3.5'

services:
  postgresql:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - ROLE=master
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/db-files/
    networks:
      postgres-net:
        aliases:
          - db
    volumes:
      - postgres-vol:/var/lib/postgresql/data

networks:
  postgres-net:
    external: true
