version: '3.5'

services:
  postgresql-slave:
    container_name: postgresql-slave
    restart: on-failure:3

networks:
  postgres-net:
    external: true

volumes:
  postgres-slave-vol:
    name: postgres-slave-vol