services:
  postgresql:
    deploy:
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}${DESIRED_WORKER_ID}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-2}'
          memory: ${RESOURCES_LIMITS_MEMORY:-1G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-512M}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: ${DATA_VOL_BACKING:-relocatable}
      size: ${DATA_VOL_SIZE:-20}
      ebstype: ${DATA_VOL_EBSTYPE:-gp2}

  wal-vol:
    name: ${WAL_VOL_NAME}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: ${WAL_VOL_BACKING:-relocatable}
      size: ${WAL_VOL_SIZE:-2}
      ebstype: ${WAL_VOL_EBSTYPE:-gp2}
