services:
  postgresql:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/postgres/postgresql}:${IMAGE_TAG:-latest}
    command: >
      -c shared_preload_libraries=${SHARED_PRELOAD_LIBRARIES:-pg_cron}
      -c cron.database_name=${POSTGRES_DB}
      -c work_mem=${WORK_MEM:-128MB}
      -c max_wal_size=${MAX_WAL_SIZE:-1GB}
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      PGDATA:
      POSTGRES_INITDB_WALDIR:
    networks:
      postgres-net:
        aliases:
          - db
    volumes:
      - data-vol:${PGDATA}
      - wal-vol:${POSTGRES_INITDB_WALDIR}
    healthcheck:
      disable: ${HEALTHCHECK_DISABLE:-false}
    configs:
      - source: mail-layout
        target: /home/REDMIC/Mail/dist/layout.mustache
    stop_grace_period: ${STOP_GRACE_PERIOD:-2m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}

networks:
  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    attachable: ${POSTGRES_NET_ATTACHABLE:-true}

configs:
  mail-layout:
    name: ${MAIL_LAYOUT_NAME:-mail-layout}
    file: ./config/layout.mustache
