version: '3.5'

services:
  postgresql:
    deploy:
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-128M}

volumes:
  postgres-data-vol:
    name: ${POSTGRES_DATA_VOLUME_NAME}

  postgres-wal-vol:
    name: ${POSTGRES_WAL_VOLUME_NAME}
