version: '3.5'

services:
  postgresql:
    deploy:
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-128M}

volumes:
  postgres-data-vol:
    name: ${POSTGRES_DATA_VOLUME_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE:-nfs4}
      o: addr=${VOL_ADDR:-127.0.0.1},${VOL_OPTIONS:-rw,nolock,noatime,tcp,rsize=8192,wsize=8192,timeo=14}
      device: ${POSTGRES_DATA_VOL_DEVICE:-:/postgres-data-vol/}

  postgres-wal-vol:
    name: ${POSTGRES_WAL_VOLUME_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE:-nfs4}
      o: addr=${VOL_ADDR:-127.0.0.1},${VOL_OPTIONS:-rw,nolock,noatime,tcp,rsize=8192,wsize=8192,timeo=14}
      device: ${POSTGRES_WAL_VOL_DEVICE:-:/postgres-wal-vol/}
