version: '3.5'

services:
  postgresql:
    deploy:
      placement:
        constraints:
          - node.hostname == ${PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-hostname}
      resources:
        limits:
          cpus: '${POSTGRESQL_RESOURCES_LIMITS_CPUS:-1}'
          memory: ${POSTGRESQL_RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${POSTGRESQL_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${POSTGRESQL_RESOURCES_RESERVATIONS_MEMORY:-128M}

volumes:
  postgres-data-vol:
    name: ${POSTGRES_DATA_VOLUME_NAME}

  postgres-wal-vol:
    name: ${POSTGRES_WAL_VOLUME_NAME}
