version: '3.5'

services:
  backup-db:
    image: ${BACKUP_DB_IMAGE_NAME:-registry.gitlab.com/redmic-project/postgres/backup-db}:${BACKUP_DB_IMAGE_TAG:-latest}
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOSTNAME:
      BUCKET_BACKUP_DB:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      PUSHGATEWAY_HOST:
      PUSHGATEWAY_JOB:
    networks:
      postgres-net:
      metric-net:
    deploy:
      mode: replicated
      replicas: ${BACKUP_DB_REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: ${BACKUP_DB_RESTART_DELAY:-30s}
      resources:
        limits:
          cpus: '${BACKUP_DB_RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${BACKUP_DB_RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${BACKUP_DB_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${BACKUP_DB_RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  postgres-net:
    name: ${POSTGRES_NET_NAME}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true
