version: '3.5'

services:
  postgresql:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}${DESIRED_WORKER_ID}
      restart_policy:
        condition: on-failure
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1639M

volumes:
  postgres-data-vol:
    name: "postgres-data-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 10
      ebstype: gp2

  postgres-wal-vol:
    name: "postgres-wal-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 10
      ebstype: gp2
