version: '3.5'

services:
  postgresql:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/postgres/postgresql}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        POSTGRES_IMAGE_TAG:
        LOCALES_VERSION:
        PLPYTHON3_VERSION:
        PYTHON3_PYSTACHE_VERSION:
        PGCRON_VERSION:
        POSTGIS_MAJOR:
        POSTGIS_VERSION:
        GETTEXT_BASE_VERSION:
    environment:
      ROLE:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA:
      POSTGRES_INITDB_WALDIR:
    networks:
      postgres-net:
        aliases:
          - db
    volumes:
      - postgres-data-vol:/var/lib/postgresql/data
      - postgres-wal-vol:/postgresql/wal
    configs:
      - source: mail-layout
        target: /home/REDMIC/Mail/dist/layout.mustache
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}

networks:
  postgres-net:
    name: ${POSTGRES_NET_NAME}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    attachable: ${POSTGRES_NET_ATTACHABLE:-true}

configs:
  mail-layout:
    name: ${MAIL_LAYOUT_NAME:-mail-layout}
    file: ./config/layout.mustache
