version: '3.5'

services:
  postgresql:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      ROLE:
      POSTGRES_PASSWORD:
      PGDATA:
      POSTGRES_INITDB_WALDIR:
    networks:
      postgres-net:
        aliases:
          - db
    volumes:
      - postgres-data-vol:/var/lib/postgresql/data
      - postgres-wal-vol:/postgresql/wal
    configs:
      - source: mail-layout
        target: /home/REDMIC/Mail/dist/layout.mustache
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 10s
        window: 1m

networks:
  postgres-net:
    name: ${POSTGRES_NET_NAME}
    external: true

configs:
  mail-layout:
    name: ${MAIL_LAYOUT_NAME:-mail-layout}
    file: ./config/layout.mustache
