version: '3.5'

services:
  postgresql:
    deploy:
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}${DESIRED_WORKER_ID}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-2}'
          memory: ${RESOURCES_LIMITS_MEMORY:-1G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-512M}

volumes:
  postgres-data-vol:
    name: ${POSTGRES_DATA_VOLUME_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: ${POSTGRES_DATA_VOLUME_SIZE:-20}
      ebstype: gp2

  postgres-wal-vol:
    name: ${POSTGRES_WAL_VOLUME_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: ${POSTGRES_WAL_VOLUME_SIZE:-10}
      ebstype: gp2
