version: '3.5'

services:
  postgresql:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - ROLE
      - POSTGRES_PASSWORD
      - PGDATA
      - POSTGRES_INITDB_WALDIR
    networks:
      postgres-net:
        aliases:
          - db
    volumes:
      - postgres-data-vol:/var/lib/postgresql/data
      - postgres-wal-vol:/postgresql/wal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 1m
        window: 3m

networks:
  postgres-net:
    external: true
