version: '3.5'

services:
  postgresql:
    deploy:
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}${DESIRED_WORKER_ID}
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1639M

volumes:
  postgres-data-vol:
    name: ${POSTGRES_DATA_VOLUME_NAME:-postgres-data-vol}
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 10
      ebstype: gp2

  postgres-wal-vol:
    name: ${POSTGRES_WAL_VOLUME_NAME:-postgres-wal-vol}
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 10
      ebstype: gp2
