version: '3.5'

services:
  postgresql:
    ports:
      - target: 5432
        published: 5432
        mode: host
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          memory: 820M
