version: '3.5'

services:
  postgresql:
    ports:
      - target: ${PORT}
        published: ${PORT}
        mode: host
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.001'
          memory: 128M

volumes:
  postgres-data-vol:
    name: ${POSTGRES_DATA_VOLUME_NAME}

  postgres-wal-vol:
    name: ${POSTGRES_WAL_VOLUME_NAME}
