version: '3.5'

services:
  postgresql:
    image: ${POSTGRESQL_IMAGE_NAME:-registry.gitlab.com/redmic-project/postgres/postgresql}:${POSTGRESQL_IMAGE_TAG:-latest}
    environment:
      ROLE:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA:
      POSTGRES_INITDB_WALDIR:
    networks:
      postgres-net:
        aliases:
          - db
    volumes:
      - postgres-data-vol:/var/lib/postgresql/data
      - postgres-wal-vol:/postgresql/wal
    configs:
      - source: mail-layout
        target: /home/REDMIC/Mail/dist/layout.mustache
    deploy:
      mode: replicated
      replicas: ${POSTGRESQL_REPLICAS:-1}
      restart_policy:
        delay: ${POSTGRESQL_RESTART_DELAY:-10s}
      update_config:
        delay: ${POSTGRESQL_UPDATE_DELAY:-1m}

networks:
  postgres-net:
    name: ${POSTGRES_NET_NAME}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    attachable: ${POSTGRES_NET_ATTACHABLE:-true}

configs:
  mail-layout:
    name: ${MAIL_LAYOUT_NAME:-mail-layout}
    file: ./config/layout.mustache
