#!/usr/bin/env bash
set -Eeo pipefail

CONFIG_FILENAME="postgresql"

if [[ "${ROLE}" == "master" ]]; then

	export PG_MAX_WAL_SENDERS=${PG_MAX_WAL_SENDERS:-8}
	export PG_MAX_REPLICATION_SLOTS=${PG_MAX_REPLICATION_SLOTS:-8}
	export PG_MAX_LOGICAL_REPLICATION_WORKERS=${PG_MAX_LOGICAL_REPLICATION_WORKERS:-0}
	export PG_MAX_WORKER_PROCESSES=${PG_MAX_WORKER_PROCESSES:-}
else
	export PG_MAX_WAL_SENDERS=${PG_MAX_WAL_SENDERS:-0}
	export PG_MAX_REPLICATION_SLOTS=${PG_MAX_REPLICATION_SLOTS:-4}
	export PG_MAX_LOGICAL_REPLICATION_WORKERS=${PG_MAX_LOGICAL_REPLICATION_WORKERS:-6}
	export PG_MAX_WORKER_PROCESSES=${PG_MAX_WORKER_PROCESSES:-$PG_MAX_LOGICAL_REPLICATION_WORKERS+1}
fi

envsubst < /tmp/${CONFIG_FILENAME}.template > /usr/share/postgresql/${PG_MAJOR}/${CONFIG_FILENAME}.conf.sample

exec "docker-entrypoint-origin.sh" "$@"